# Generated by Django 5.0.6 on 2024-07-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_blog_content_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
